### ISSUE TITLE
Update gru node version and remove git

### ISSUE THREAD

**Issue by timothycraig** [frameshiftgenomics/iobio-services#39]
@anderspitman Any chance you can squeeze these items into your next release (or at least put them on the roadmap for later this year)?

`gru/docker/prod/Dockerfile`

- [ ] Update to at least node v16 or even v18

`ARG node_version=12.x`

12.x is not maintained anymore.  I don't think there should be any breaking changes

- [ ] Remove `git` from dependencies.  Now that we're not cloning the repo, I don't think git is needed.
- [ ] Update npm packages for gru and gene.  This isn't essential, but at some point it's probably a good idea to update to resolve any security vulnerabilities.

Don’t want to burden you so these are just some suggestions, but as I was debugging these issues came to mind.

**Comment by anderspitman** [comment]
@timothycraig I'm working on the release now and will try to get all this in there. Thanks for the suggestions.

**Comment by timothycraig** [comment]
Resolved in https://github.com/frameshiftgenomics/iobio-services/commit/8fcee8f57a74b4ae83eb52d46758ca52a9292ff0
